export const getRewardsData = (bountyBalance, bountyBalanceUSD) => [
    {
        key: 'wETH',
        image: 'images/currency/weth.png',
        alt: 'wETH Icon',
        value: bountyBalance.wETH,
        label: 'WETH',
    },
    {
        key: 'Mana',
        image: 'images/currency/mana.png',
        alt: 'mana Icon',
        value: bountyBalance.Mana,
        label: 'MANA',
    },
    {
        key: 'GEM',
        image: 'images/currency/gem.png',
        alt: 'gem Icon',
        value: bountyBalance.GEM,
        label: 'GEMs',
    },
    {
        key: 'cards',
        image: 'https://media.mythicalbeings.io/sm/mythical68.jpg',
        alt: 'special cards Icon',
        value: 7,
        label: 'SPECIAL CARDS',
        customSize: { h: '40px' },
    },
    {
        key: 'items',
        image: '/images/items/WaterCristaline copia.png',
        alt: 'potions Icon',
        value: bountyBalance.Items,
        label: 'POTIONS',
    },
    {
        key: 'total',
        image: '/images/currency/multicurrency.png',
        alt: 'total bounty Icon',
        value: bountyBalanceUSD.Total.toFixed(2),
        label: 'USD TOTAL BOUNTY',
    },
];
